In [ ]:
import pandas as pd

In [ ]:
data1 = pd.read_csv('/content/drive/Shareddrives/2021 CCP/천신만고 끝에 얻은 데이터/KT 데이터 재구성/extend_ver/202107KT_ymdmf.csv')
data1 = data1.drop(['Unnamed: 0'], axis=1)
data1

          etl_ymd        id           x          y  ...   50s   60s   70s   80s
0        20210701  51764393  127.029783  37.581530  ...  0.67  0.59  0.07  0.00
1        20210701  51764394  127.029778  37.581981  ...  0.73  0.67  0.07  0.00
2        20210701  51764395  127.029772  37.582431  ...  0.79  0.72  0.08  0.00
3        20210701  51764396  127.029766  37.582881  ...  0.68  0.62  0.07  0.00
4        20210701  51776582  127.030349  37.581535  ...  0.80  0.72  0.08  0.00
...           ...       ...         ...        ...  ...   ...   ...   ...   ...
2478833  20210731  49728772  126.935629  37.554590  ...  8.78  3.09  2.58  0.78
2478834  20210731  49728773  126.935622  37.555040  ...  0.49  0.36  0.24  0.00
2478835  20210731  49728774  126.935616  37.555491  ...  0.56  0.42  0.28  0.00
2478836  20210731  49740962  126.936188  37.555045  ...  0.93  0.69  0.46  0.00
2478837  20210731  49753151  126.936754  37.555050  ...  0.00  0.22  0.00  0.00

[2478838 rows x 78 columns]

In [ ]:
data = data1[['year','month','day','timezn_cd','week','weekday','holiday','id','x','y','admi_cd','total','male','female']]

In [ ]:
data['young'] = data1['m20'] + data1['m25'] + data1['f20'] + data1['f25']
data['middle'] = data1['m30'] + data1['m35'] + data1['m40'] + data1['m45'] + data1['f30'] + data1['f35'] + data1['f40'] + data1['f45']
data['older'] = data1['m50'] + data1['m55'] + data1['m60'] + data1['f50'] + data1['f55'] + data1['f60']
data['oldest'] = data1['m65'] + data1['m70'] + data1['m75'] + data1['m80'] + data1['m85'] + data1['f65'] + data1['f70'] + data1['f75'] + data1['f80'] + data1['f85']

In [ ]:
weather = pd.read_csv('/content/drive/Shareddrives/2021 CCP/천신만고 끝에 얻은 데이터/2022.01.28/2021.07.tr.csv')
corona = pd.read_excel('/content/drive/Shareddrives/2021 CCP/천신만고 끝에 얻은 데이터/2022.01.28/2021.07.xlsx')

In [ ]:
data['temperature'] = 0
data['rain'] = 0
data['corona'] = 0

In [ ]:
for i in range(len(weather)):
  data.loc[data['day'] == int(weather['date'][i][7:]), ['temperature','rain']] = [weather['temperature'][i],weather['rain'][i]]

In [ ]:
for i in range(len(corona)):
  data.loc[data['day'] == corona['day'][i], ['corona']] = corona['confirmed'][i]

In [ ]:
data.to_csv("/content/drive/Shareddrives/2021 CCP/천신만고 끝에 얻은 데이터/2022.01.28/202107_add.csv", mode='w', index = None)

In [ ]:
data

         year  month  day  timezn_cd  ...  oldest  temperature  rain  corona
0        2021      7    1          0  ...    0.33         26.3   0.0     375
1        2021      7    1          0  ...    0.37         26.3   0.0     375
2        2021      7    1          0  ...    0.40         26.3   0.0     375
3        2021      7    1          0  ...    0.35         26.3   0.0     375
4        2021      7    1          0  ...    0.40         26.3   0.0     375
...       ...    ...  ...        ...  ...     ...          ...   ...     ...
2478833  2021      7   31         23  ...    4.65         29.8   3.0     488
2478834  2021      7   31         23  ...    0.36         29.8   3.0     488
2478835  2021      7   31         23  ...    0.42         29.8   3.0     488
2478836  2021      7   31         23  ...    0.69         29.8   3.0     488
2478837  2021      7   31         23  ...    0.22         29.8   3.0     488

[2478838 rows x 21 columns]